apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8080":{"name": "gateway-service-neg"}}}'
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP