apiVersion: apps/v1
kind: Deployment
metadata:
  name: veo-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veo-service
  template:
    metadata:
      labels:
        app: veo-service
    spec:
      containers:
      - name: veo-service
        image: gcr.io/your-gcp-project-id/veo-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20