steps:
  # Build and push gateway-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gateway-service:$COMMIT_SHA', '.']
    dir: 'backend/gateway-service'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gateway-service:$COMMIT_SHA']

  # Build and push agent-orchestrator image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/agent-orchestrator:$COMMIT_SHA', '.']
    dir: 'backend/agent-orchestrator'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agent-orchestrator:$COMMIT_SHA']

  # Build and push veo-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/veo-service:$COMMIT_SHA', '.']
    dir: 'backend/veo-service'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/veo-service:$COMMIT_SHA']

  # Build and push imagen-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/imagen-service:$COMMIT_SHA', '.']
    dir: 'backend/imagen-service'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/imagen-service:$COMMIT_SHA']

  # Build and push mentor-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mentor-service:$COMMIT_SHA', '.']
    dir: 'backend/mentor-service'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mentor-service:$COMMIT_SHA']

  # Build and push analytics-service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/analytics-service:$COMMIT_SHA', '.']
    dir: 'backend/analytics-service'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/analytics-service:$COMMIT_SHA']

  # Build and push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '.']
    dir: 'frontend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=infra/kubernetes'
      - '--image=gcr.io/$PROJECT_ID/gateway-service:$COMMIT_SHA'
      - '--location=us-central1' # Replace with your GKE cluster location
      - '--cluster=veyoo-gke-cluster' # Replace with your GKE cluster name 